eureka:
  client:
    service-url:
      default-zone: http://localhost:8671:/eureka/
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    stream:
      bindings:
	input:
          destination: learning-spring-boot-comment
          group: learning-spring-boot
        output:
          destination: learning-spring-boot-comment
          group: learning-spring-boot
